/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FilterCondition {
  modes?: Mode[];
  stages?: StageFilter;
  rules?: Rule[];
  timeSlots?: TimeSlot[];
}
export interface StageFilter {
  matchBothStages: boolean;
  stageIds: number[];
}
export interface TimeSlot {
  start: string;
  end: string;
  dayOfWeek?: DayOfWeek;
}

export enum Language {
  ja = "ja",
  en = "en"
}
export enum Mode {
  bankara_open = "bankara_open",
  bankara_challenge = "bankara_challenge",
  x = "x",
  regular = "regular",
  event = "event"
}
export enum Rule {
  nawabari = "nawabari",
  area = "area",
  yagura = "yagura",
  hoko = "hoko",
  asari = "asari"
}
export enum DayOfWeek {
  sun = "sun",
  mon = "mon",
  tue = "tue",
  wed = "wed",
  thu = "thu",
  fri = "fri",
  sat = "sat"
}
