name: spla-ical
github: "github.com/nokoika/spla-ical"
author: "nokoika"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/spla-ical#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - time
  - hspec
  - scotty
  - aeson
  - base64-bytestring
  - bytestring
  - http-conduit
  - http-types
  - cache
  - memory
  - cryptonite
  - hlint
  - ormolu

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Werror # すべての警告をエラーとして扱う

default-extensions:
  - NoImplicitPrelude
  - StrictData
  - ScopedTypeVariables
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - BangPatterns
  - LambdaCase
  - ViewPatterns
  - PatternSynonyms
  - DuplicateRecordFields
  - NamedFieldPuns
  - RecordWildCards
  - TypeOperators
  - KindSignatures
  - GADTs
  - DataKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - GeneralizedNewtypeDeriving
  - TupleSections
  - OverloadedStrings
  - Arrows
  - RecursiveDo
  - DeriveGeneric # Aeson のため

library:
  source-dirs: src

executables:
  spla-ical-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - spla-ical

tests:
  spla-ical-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - spla-ical
