name: "Haskell CI"

on:
  pull_request: null
  push:
    branches:
      - "main"

env:
  GHC_VERSION: "9.4.8"

jobs:
  build-and-check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Cache stack's global packages"
        uses: "actions/cache@v4"
        with:
          path: "~/.stack"
          key: "\
            ${{ runner.os }}-stack\
            -${{ hashFiles('**/stack.yaml.lock') }}\
            -${{ hashFiles('**/package.yaml') }}\
          "
          restore-keys: "${{ runner.os }}-stack-"
      - name: "Setup GHC and stack"
        uses: "haskell-actions/setup@v2"
        with:
          ghc-version: "${{ env.GHC_VERSION }}"
          enable-stack: true
          stack-version: "latest"
      - name: "Install dependencies"
        run: "stack --system-ghc build --only-dependencies"
      - name: "Lint"
        run: "stack --system-ghc exec -- hlint app/ src/ test/"
      - name: "Format check"
        run: |
          find app/ src/ test/ -name "*.hs" | xargs -n1 stack exec -- ormolu --mode check
      - name: "Build"
        run: "stack --system-ghc build"
      - name: "Unit Test"
        run: "stack --system-ghc test"
      - name: "E2E Test"
        run: |
          set -x

          stack --system-ghc exec -- spla-ical-exe &
          API_PID=$!
          # テストが終わったらサーバーを停止
          trap 'kill $API_PID && echo "API server stopped"' EXIT
          sleep 1
          ./test/e2e.sh
