name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-stack@v2
        with:
          stack-version: '3.1.1'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            ~/.local/bin
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - run: stack setup
      - run: stack build
      - run: stack exec -- hlint app/ src/ test/ --report=hlint-report.txt
      - run: |
          find app/ src/ test/ -name "*.hs" | xargs -n1 stack exec -- ormolu --mode check
      - run: stack test
