name: "Haskell CI"

on:
  pull_request: null
  push:
    branches:
      - "main"

env:
  GHC_VERSION: "9.4.8"

jobs:
  build-and-check:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/cache@v4"
        with:
          path: "~/.stack"
          key: "\
            ${{ runner.os }}-stack\
            -${{ hashFiles('**/stack.yaml.lock') }}\
            -${{ hashFiles('**/package.yaml') }}\
          "
          restore-keys: "${{ runner.os }}-stack-"
      - uses: "haskell-actions/setup@v2"
        with:
          ghc-version: "${{ env.GHC_VERSION }}"
          enable-stack: true
          stack-version: "latest"
      - run: "stack --system-ghc test"
      - run: "stack --system-ghc build"
      - run: "stack --system-ghc exec -- hlint app/ src/ test/"
      - run: |
          find app/ src/ test/ -name "*.hs" | xargs -n1 stack exec -- ormolu --mode check
